### ISSUE TITLE
insert id's of vaccination place's

### ISSUE THREAD

**Issue by chnuessli** [openZH/covid_19_vaccination_campaign_ZH#2]
Wouldn't it be nice for statistics, to have id's of vaccination places?

**Comment by andreasamsler** [comment]
Thanks for the input, @chnuessli. Some first notes:

- For privacy reasons (both regarding persons vaccinated/not vaccinated and vaccination places ('institutions/organisations') these location related data would need to be anonymised (likely with 'hashes').
- Hashes could probably be matched to places ('types') of vaccination (see https://github.com/openZH/covid_19_vaccination_campaign_ZH/issues/1).
- The additional info would be: how many vaccination places are active over time per vaccination place ('type') and with what individual performance.

Next step:

- We are discussing feasibility with our colleagues at @GD-ZH.
