### ISSUE TITLE
Use same formatting of age-categories as other openzh and bag-apis

### ISSUE THREAD

**Issue by rsalzer** [openZH/covid_19_vaccination_campaign_ZH#4]
It would be nice if the age-categories could be the same as in other repos:
0-9
10-19
...
80+

For example here:
https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_alter_geschlecht_csv/COVID19_Einwohner_Kanton_ZH_altersklassen_geschlecht.csv
Or also BAG (there its also with additional whitespace ... which is not really needed):
https://www.covid19.admin.ch/api/data/20210430-zza0vm8q/sources/COVID19FullyVaccPersons_AKL10_w.csv

**Comment by andreasamsler** [comment]
Resolved.
